cb_cluster:
  nodes_init: 4
  services:
    - "kv"
    - "kv"
    - "index,n1ql"
    - "backup,cbas"

  settings:
    - name: "memory_quota"
      memoryQuota: 2048
      indexMemoryQuota: 2048
      ftsMemoryQuota: 512
      cbasMemoryQuota: 1024
      eventingMemoryQuota: 512

  rbac_users:
    - user_name: "cluster_admin"
      password: "cluster_admin"
      roles:
        - "cluster_admin"
    - user_name: "rbac_admin"
      password: "rbac_admin"
      roles:
        - "security_admin_local"
