cb_cluster:
  nodes_init: 4
  services:
    - "kv"
    - "kv"
    - "index,n1ql"
    - "backup,cbas,index"

  rbac_users:
    - user_name: "cluster_admin"
      password: "cluster_admin"
      roles:
        - "cluster_admin"
    - user_name: "rbac_admin"
      password: "rbac_admin"
      roles:
        - "security_admin_local"
