cb_cluster:
  nodes_init: 4
  services:
    - "kv"
    - "kv"
    - "index,n1ql"
    - "backup,cbas"

  settings:
    - name: "memory_quota"
      indexMemoryQuota: 2048
      ftsMemoryQuota: 512
      cbasMemoryQuota: 1024
      eventingMemoryQuota: 512
      # Use in case of Vol. testing
      # memoryQuota: 2048
      # indexMemoryQuota: 4096
      # ftsMemoryQuota: 4096
      # cbasMemoryQuota: 2048
      # eventingMemoryQuota: 2048

  rbac_users:
    - user_name: "cluster_admin"
      password: "Cluster_admin@123"
      roles:
        - "cluster_admin"
    - user_name: "rbac_admin"
      password: "Rbac_admin@123"
      roles:
        - "security_admin_local"
