buckets:
  - name: "travel-sample"
    sample_bucket: True
    replicas: 1
    ramQuotaMB: 1024
    scopes:
      - name: "agent_1"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 200
      - name: "agent_2"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 200
      - name: "agent_3"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 300
      - name: "agent_4"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 600
      - name: "agent_5"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 900
